### ISSUE TITLE
Featured picture overlaps with the title if turning off reading time and post date

### ISSUE THREAD

**Issue by dimkagabber** [jpanther/congo#910] opened 2024-07-13 08:11 UTC
### Discussed in https://github.com/jpanther/congo/discussions/909

<div type='discussions-op-text'>

<sup>Originally posted by **dimkagabber** July 13, 2024</sup>
Subj.

params.toml:
```
[article]
 showDate = false
 showReadingTime = false
```
![image](https://github.com/user-attachments/assets/53b6e99b-a055-47f8-916b-0635328694b9)

params.toml:
```
[article]
 showDate = false
 showReadingTime = true
```
![image](https://github.com/user-attachments/assets/6564330d-61c4-4234-b38f-e3451ad25823)
</div>

**Comment by jpanther** [comment] 2024-08-29 00:46
Duplicate of #827

**Closed as not planned by jpanther** 2024-08-29 00:46 UTC
Labels: duplicate
